name: LWI.com
favicon: null
layout_spectrum: 0.6595
typography_spectrum: 0.16105
title: Welcome to LWI.COM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffd27f'
    - '#db5c3b'
    - '#000000'
    - '#5b6668'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
