name: LWI.com
favicon: null
layout_spectrum: 0.2551
typography_spectrum: 0.61124
title: Graphic Design and Production
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffd27f'
    - '#db5c3b'
    - '#000000'
    - '#5b6668'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
