name: LWI.com
favicon: null
layout_spectrum: 0.9723404
typography_spectrum: 0.60167
title: Graphic Design and Production
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#212121'
    - '#da5a3f'
    - '#b9b9b9'
    - '#40b565'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
